version: "2"

# Find the whole list here https://golangci-lint.run/usage/linters/
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - durationcheck
    - errcheck
    - errorlint
    - forbidigo
    - gomoddirectives
    - gomodguard
    - gosec
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - staticcheck
    - unconvert
    - unused
    - wastedassign
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: math/rand$
              desc: superseded by math/rand/v2
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - (mapstr.M).Delete
        - (mapstr.M).Put
    errorlint:
      errorf: true
      asserts: true
      comparison: true
    forbidigo:
      forbid:
        - pattern: fmt.Print.* # too much log noise
      exclude-godoc-examples: true
    gomoddirectives:
      replace-local: false
    gomodguard:
      blocked:
        modules:
          - github.com/pkg/errors:
              recommendations:
                - errors
                - fmt
              reason: This package is deprecated, use fmt.Errorf with %%w instead
          - github.com/elastic/beats/v7:
              reason: There must be no Beats dependency
    gosec:
      excludes:
        - G306 # Expect WriteFile permissions to be 0600 or less
        - G404 # Use of weak random number generator
        - G401 # Detect the usage of DES, RC4, MD5 or SHA1: Used in non-crypto contexts.
        - G501 # Import blocklist: crypto/md5: Used in non-crypto contexts.
        - G505 # Import blocklist: crypto/sha1: Used in non-crypto contexts.
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
