# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

steps:
  - label: "Lint"
    command:
      - ".buildkite/scripts/lint.sh"
    agents:
      image: golang:${GO_VERSION}
      cpu: "8"
      memory: "4G"

  - label: "Test Linux"
    command:
      - ".buildkite/scripts/test.sh"
    agents:
      image: golang:${GO_VERSION}
      cpu: "8"
      memory: "4G"
    artifact_paths:
      - "junit-*.xml"
