#!/bin/bash
set -euo pipefail

# addtional preparation for macos step
if [[ "$BUILDKITE_PIPELINE_SLUG" == "elastic-agent-libs" && "$BUILDKITE_STEP_KEY" == "test-mac" ]]; then
    echo "--- prepare env"
    source .buildkite/scripts/pre-install-command.sh
    with_go ${GO_VERSION} ${SETUP_GVM_VERSION}
fi
